const db = admin.firestore();

// Sample offer data
const sampleOffers = [
    // Dining Offers
    {
        bankName: "HDFC",
        paymentType: "Credit Card",
        merchant: "Swiggy",
        discountType: "Percentage",
        discountValue: 50,
        maxDiscountAmount: 100,
        minOrderValue: 199,
        startDate: admin.firestore.Timestamp.now(),
        endDate: admin.firestore.Timestamp.fromDate(new Date('2025-12-31')),
        isActive: true,
        description: "Get 50% off up to ₹100 on orders above ₹199",
        sourceUrl: "https://www.swiggy.com",
        dealScore: 95,
        dealBand: "Green",
        successCount: 245,
        failCount: 5,
        category: "Dining",
        couponCode: "HDFC50"
    },
    {
        bankName: "ICICI",
        paymentType: "Debit Card",
        merchant: "Zomato",
        discountType: "Percentage",
        discountValue: 40,
        maxDiscountAmount: 80,
        minOrderValue: 149,
        startDate: admin.firestore.Timestamp.now(),
        endDate: admin.firestore.Timestamp.fromDate(new Date('2025-12-31')),
        isActive: true,
        description: "40% off up to ₹80 on Zomato orders",
        sourceUrl: "https://www.zomato.com",
        dealScore: 88,
        dealBand: "Green",
        successCount: 189,
        failCount: 8,
        category: "Dining",
        couponCode: "ICICI40"
    },
    {
        bankName: "SBI",
        paymentType: "Credit Card",
        merchant: "Domino's Pizza",
        discountType: "Flat",
        discountValue: 150,
        minOrderValue: 400,
        startDate: admin.firestore.Timestamp.now(),
        endDate: admin.firestore.Timestamp.fromDate(new Date('2025-12-31')),
        isActive: true,
        description: "Flat ₹150 off on orders above ₹400",
        sourceUrl: "https://www.dominos.co.in",
        dealScore: 82,
        dealBand: "Green",
        successCount: 156,
        failCount: 12,
        category: "Dining",
        couponCode: "SBI150"
    },
    // Additional Dining from sample_offers_data.js
    {
        bankName: "HDFC",
        paymentType: "Credit Card",
        merchant: "Zomato",
        discountType: "Percentage",
        discountValue: 40,
        maxDiscountAmount: 150,
        minOrderValue: 500,
        startDate: admin.firestore.Timestamp.now(),
        endDate: admin.firestore.Timestamp.fromDate(new Date('2025-12-31')),
        isActive: true,
        description: "40% off on Zomato food orders",
        sourceUrl: "https://www.zomato.com",
        dealScore: 92,
        dealBand: "Green",
        successCount: 100,
        failCount: 2,
        category: "Dining",
        couponCode: "HDFCZOM",
        termsAndConditions: "Valid on orders above ₹500. Maximum discount ₹150."
    },
    {
        bankName: "ICICI",
        paymentType: "Credit Card",
        merchant: "Swiggy",
        discountType: "Percentage",
        discountValue: 30,
        maxDiscountAmount: 120,
        minOrderValue: 400,
        startDate: admin.firestore.Timestamp.now(),
        endDate: admin.firestore.Timestamp.fromDate(new Date('2025-12-31')),
        isActive: true,
        description: "30% off on Swiggy food delivery",
        sourceUrl: "https://www.swiggy.com",
        dealScore: 88,
        dealBand: "Green",
        successCount: 85,
        failCount: 3,
        category: "Dining",
        couponCode: "ICICISWG",
        termsAndConditions: "Valid on orders above ₹400. Maximum discount ₹120."
    },

    // Travel Offers
    {
        bankName: "Axis",
        paymentType: "Credit Card",
        merchant: "MakeMyTrip",
        discountType: "Percentage",
        discountValue: 30,
        maxDiscountAmount: 3000,
        minOrderValue: 10000,
        startDate: admin.firestore.Timestamp.now(),
        endDate: admin.firestore.Timestamp.fromDate(new Date('2025-01-15')),
        isActive: true,
        description: "30% off up to ₹3000 on flight bookings",
        sourceUrl: "https://www.makemytrip.com",
        dealScore: 92,
        dealBand: "Green",
        successCount: 312,
        failCount: 15,
        category: "Travel",
        couponCode: "AXIS30"
    },
    {
        bankName: "HDFC",
        paymentType: "Credit Card",
        merchant: "Cleartrip",
        discountType: "Flat",
        discountValue: 2000,
        minOrderValue: 15000,
        startDate: admin.firestore.Timestamp.now(),
        endDate: admin.firestore.Timestamp.fromDate(new Date('2025-01-31')),
        isActive: true,
        description: "Flat ₹2000 off on international flights",
        sourceUrl: "https://www.cleartrip.com",
        dealScore: 90,
        dealBand: "Green",
        successCount: 278,
        failCount: 10,
        category: "Travel",
        couponCode: "HDFC2K"
    },
    {
        bankName: "Kotak",
        paymentType: "Debit Card",
        merchant: "Goibibo",
        discountType: "Percentage",
        discountValue: 25,
        maxDiscountAmount: 1500,
        minOrderValue: 5000,
        startDate: admin.firestore.Timestamp.now(),
        endDate: admin.firestore.Timestamp.fromDate(new Date('2025-12-31')),
        isActive: true,
        description: "25% off up to ₹1500 on hotel bookings",
        sourceUrl: "https://www.goibibo.com",
        dealScore: 85,
        dealBand: "Green",
        successCount: 198,
        failCount: 18,
        category: "Travel",
        couponCode: "KOTAK25"
    },

    // Shopping Offers
    {
        bankName: "ICICI",
        paymentType: "Credit Card",
        merchant: "Amazon",
        discountType: "Percentage",
        discountValue: 10,
        maxDiscountAmount: 1000,
        minOrderValue: 2000,
        startDate: admin.firestore.Timestamp.now(),
        endDate: admin.firestore.Timestamp.fromDate(new Date('2025-12-31')),
        isActive: true,
        description: "10% instant discount up to ₹1000",
        sourceUrl: "https://www.amazon.in",
        dealScore: 78,
        dealBand: "Yellow",
        successCount: 445,
        failCount: 25,
        category: "Shopping",
        couponCode: "ICICI10"
    },
    {
        bankName: "SBI",
        paymentType: "Debit Card",
        merchant: "Flipkart",
        discountType: "Percentage",
        discountValue: 15,
        maxDiscountAmount: 750,
        minOrderValue: 1500,
        startDate: admin.firestore.Timestamp.now(),
        endDate: admin.firestore.Timestamp.fromDate(new Date('2025-12-31')),
        isActive: true,
        description: "15% off up to ₹750 on electronics",
        sourceUrl: "https://www.flipkart.com",
        dealScore: 80,
        dealBand: "Green",
        successCount: 367,
        failCount: 22,
        category: "Shopping",
        couponCode: "SBI15"
    },
    {
        bankName: "Axis",
        paymentType: "Credit Card",
        merchant: "Myntra",
        discountType: "Percentage",
        discountValue: 20,
        maxDiscountAmount: 500,
        minOrderValue: 1000,
        startDate: admin.firestore.Timestamp.now(),
        endDate: admin.firestore.Timestamp.fromDate(new Date('2025-12-31')),
        isActive: true,
        description: "20% off up to ₹500 on fashion",
        sourceUrl: "https://www.myntra.com",
        dealScore: 75,
        dealBand: "Yellow",
        successCount: 289,
        failCount: 30,
        category: "Shopping",
        couponCode: "AXIS20"
    },

    // Entertainment Offers
    {
        bankName: "HDFC",
        paymentType: "Credit Card",
        merchant: "BookMyShow",
        discountType: "Percentage",
        discountValue: 50,
        maxDiscountAmount: 150,
        minOrderValue: 300,
        startDate: admin.firestore.Timestamp.now(),
        endDate: admin.firestore.Timestamp.fromDate(new Date('2025-12-31')),
        isActive: true,
        description: "50% off up to ₹150 on movie tickets",
        sourceUrl: "https://www.bookmyshow.com",
        dealScore: 88,
        dealBand: "Green",
        successCount: 512,
        failCount: 18,
        category: "Entertainment",
        couponCode: "HDFC50BMS"
    },
    {
        bankName: "ICICI",
        paymentType: "UPI",
        merchant: "Netflix",
        discountType: "Flat",
        discountValue: 200,
        minOrderValue: 500,
        startDate: admin.firestore.Timestamp.now(),
        endDate: admin.firestore.Timestamp.fromDate(new Date('2025-01-31')),
        isActive: true,
        description: "Flat ₹200 off on annual subscription",
        sourceUrl: "https://www.netflix.com",
        dealScore: 85,
        dealBand: "Green",
        successCount: 234,
        failCount: 12,
        category: "Entertainment",
        couponCode: "ICICI200"
    },

    // Groceries Offers (Existing + New)
    {
        bankName: "SBI",
        paymentType: "Debit Card",
        merchant: "BigBasket",
        discountType: "Percentage",
        discountValue: 25,
        maxDiscountAmount: 300,
        minOrderValue: 1000,
        startDate: admin.firestore.Timestamp.now(),
        endDate: admin.firestore.Timestamp.fromDate(new Date('2025-12-31')),
        isActive: true,
        description: "25% off up to ₹300 on groceries",
        sourceUrl: "https://www.bigbasket.com",
        dealScore: 82,
        dealBand: "Green",
        successCount: 398,
        failCount: 20,
        category: "Groceries",
        couponCode: "SBI25BB"
    },
    {
        bankName: "Kotak",
        paymentType: "Credit Card",
        merchant: "Blinkit",
        discountType: "Flat",
        discountValue: 100,
        minOrderValue: 500,
        startDate: admin.firestore.Timestamp.now(),
        endDate: admin.firestore.Timestamp.fromDate(new Date('2025-12-31')),
        isActive: true,
        description: "Flat ₹100 off on orders above ₹500",
        sourceUrl: "https://www.blinkit.com",
        dealScore: 78,
        dealBand: "Yellow",
        successCount: 267,
        failCount: 28,
        category: "Groceries",
        couponCode: "KOTAK100"
    },
    {
        bankName: "HDFC",
        paymentType: "Credit Card",
        merchant: "BigBasket",
        discountType: "Percentage",
        discountValue: 15,
        maxDiscountAmount: 200,
        minOrderValue: 1000,
        startDate: admin.firestore.Timestamp.now(),
        endDate: admin.firestore.Timestamp.fromDate(new Date('2025-12-31')),
        isActive: true,
        description: "Get 15% off on your grocery shopping at BigBasket",
        sourceUrl: "https://www.bigbasket.com",
        dealScore: 85,
        dealBand: "Green",
        successCount: 120,
        failCount: 5,
        category: "Groceries",
        couponCode: "HDFC15",
        termsAndConditions: "Valid on orders above ₹1000. Maximum discount ₹200."
    },
    {
        bankName: "ICICI",
        paymentType: "Debit Card",
        merchant: "Zepto",
        discountType: "Flat",
        discountValue: 100,
        maxDiscountAmount: 100,
        minOrderValue: 500,
        startDate: admin.firestore.Timestamp.now(),
        endDate: admin.firestore.Timestamp.fromDate(new Date('2025-12-31')),
        isActive: true,
        description: "Flat ₹100 off on Zepto grocery orders",
        sourceUrl: "https://www.zeptonow.com",
        dealScore: 80,
        dealBand: "Green",
        successCount: 95,
        failCount: 4,
        category: "Groceries",
        couponCode: "ICICI100",
        termsAndConditions: "Valid on orders above ₹500. One time use per user."
    },
    {
        bankName: "SBI",
        paymentType: "Credit Card",
        merchant: "Blinkit",
        discountType: "Percentage",
        discountValue: 20,
        maxDiscountAmount: 150,
        minOrderValue: 800,
        startDate: admin.firestore.Timestamp.now(),
        endDate: admin.firestore.Timestamp.fromDate(new Date('2025-12-31')),
        isActive: true,
        description: "20% off on Blinkit grocery delivery",
        sourceUrl: "https://www.blinkit.com",
        dealScore: 90,
        dealBand: "Green",
        successCount: 150,
        failCount: 2,
        category: "Groceries",
        couponCode: "SBI20",
        termsAndConditions: "Valid on orders above ₹800. Maximum discount ₹150."
    },
    {
        bankName: "Axis",
        paymentType: "Credit Card",
        merchant: "DMart Ready",
        discountType: "Percentage",
        discountValue: 10,
        maxDiscountAmount: 100,
        minOrderValue: 500,
        startDate: admin.firestore.Timestamp.now(),
        endDate: admin.firestore.Timestamp.fromDate(new Date('2025-12-31')),
        isActive: true,
        description: "10% off on DMart Ready grocery orders",
        sourceUrl: "https://www.dmart.in",
        dealScore: 70,
        dealBand: "Yellow",
        successCount: 60,
        failCount: 10,
        category: "Groceries",
        couponCode: "AXIS10",
        termsAndConditions: "Valid on orders above ₹500. Maximum discount ₹100."
    },

    // Bill Pay & Recharges Offers
    {
        bankName: "HDFC",
        paymentType: "Credit Card",
        merchant: "Paytm",
        discountType: "Percentage",
        discountValue: 5,
        maxDiscountAmount: 50,
        minOrderValue: 500,
        startDate: admin.firestore.Timestamp.now(),
        endDate: admin.firestore.Timestamp.fromDate(new Date('2025-12-31')),
        isActive: true,
        description: "5% cashback on electricity bill payments via Paytm",
        sourceUrl: "https://paytm.com",
        dealScore: 75,
        dealBand: "Green",
        successCount: 200,
        failCount: 15,
        category: "Bill Pay & Recharges",
        couponCode: "HDFCBILL",
        termsAndConditions: "Valid on electricity bill payments above ₹500. Maximum cashback ₹50."
    },
    {
        bankName: "ICICI",
        paymentType: "UPI",
        merchant: "PhonePe",
        discountType: "Flat",
        discountValue: 30,
        maxDiscountAmount: 30,
        minOrderValue: 200,
        startDate: admin.firestore.Timestamp.now(),
        endDate: admin.firestore.Timestamp.fromDate(new Date('2025-12-31')),
        isActive: true,
        description: "Flat ₹30 cashback on mobile recharges",
        sourceUrl: "https://www.phonepe.com",
        dealScore: 85,
        dealBand: "Green",
        successCount: 300,
        failCount: 5,
        category: "Bill Pay & Recharges",
        couponCode: "ICICIPE",
        termsAndConditions: "Valid on mobile recharges of ₹200 and above."
    },
    {
        bankName: "SBI",
        paymentType: "Debit Card",
        merchant: "Google Pay",
        discountType: "Percentage",
        discountValue: 10,
        maxDiscountAmount: 100,
        minOrderValue: 1000,
        startDate: admin.firestore.Timestamp.now(),
        endDate: admin.firestore.Timestamp.fromDate(new Date('2025-12-31')),
        isActive: true,
        description: "10% cashback on DTH recharges via Google Pay",
        sourceUrl: "https://pay.google.com",
        dealScore: 80,
        dealBand: "Green",
        successCount: 180,
        failCount: 8,
        category: "Bill Pay & Recharges",
        couponCode: "SBIGPAY",
        termsAndConditions: "Valid on DTH recharges above ₹1000. Maximum cashback ₹100."
    },
    {
        bankName: "Axis",
        paymentType: "Credit Card",
        merchant: "CRED",
        discountType: "Percentage",
        discountValue: 2,
        maxDiscountAmount: 200,
        minOrderValue: 5000,
        startDate: admin.firestore.Timestamp.now(),
        endDate: admin.firestore.Timestamp.fromDate(new Date('2025-12-31')),
        isActive: true,
        description: "2% cashback on credit card bill payments",
        sourceUrl: "https://cred.club",
        dealScore: 70,
        dealBand: "Yellow",
        successCount: 150,
        failCount: 20,
        category: "Bill Pay & Recharges",
        couponCode: "AXISCRED",
        termsAndConditions: "Valid on credit card bill payments above ₹5000. Maximum cashback ₹200."
    },
    {
        bankName: "Kotak",
        paymentType: "UPI",
        merchant: "Airtel Thanks",
        discountType: "Flat",
        discountValue: 50,
        maxDiscountAmount: 50,
        minOrderValue: 300,
        startDate: admin.firestore.Timestamp.now(),
        endDate: admin.firestore.Timestamp.fromDate(new Date('2025-12-31')),
        isActive: true,
        description: "Flat ₹50 off on broadband bill payments",
        sourceUrl: "https://www.airtel.in",
        dealScore: 82,
        dealBand: "Green",
        successCount: 90,
        failCount: 5,
        category: "Bill Pay & Recharges",
        couponCode: "KOTAKAIR",
        termsAndConditions: "Valid on broadband bill payments of ₹300 and above."
    },
    {
        bankName: "HDFC",
        paymentType: "Debit Card",
        merchant: "Amazon Pay",
        discountType: "Percentage",
        discountValue: 8,
        maxDiscountAmount: 80,
        minOrderValue: 500,
        startDate: admin.firestore.Timestamp.now(),
        endDate: admin.firestore.Timestamp.fromDate(new Date('2025-12-31')),
        isActive: true,
        description: "8% cashback on gas cylinder bookings",
        sourceUrl: "https://www.amazon.in",
        dealScore: 88,
        dealBand: "Green",
        successCount: 110,
        failCount: 3,
        category: "Bill Pay & Recharges",
        couponCode: "HDFCGAS",
        termsAndConditions: "Valid on gas cylinder bookings via Amazon Pay."
    },

    // Wallet/UPI Offers
    {
        bankName: "Paytm",
        paymentType: "Wallet",
        merchant: "Paytm Mall",
        discountType: "Percentage",
        discountValue: 30,
        maxDiscountAmount: 200,
        minOrderValue: 500,
        startDate: admin.firestore.Timestamp.now(),
        endDate: admin.firestore.Timestamp.fromDate(new Date('2025-12-31')),
        isActive: true,
        description: "30% cashback up to ₹200",
        sourceUrl: "https://www.paytm.com",
        dealScore: 72,
        dealBand: "Yellow",
        successCount: 445,
        failCount: 35,
        category: "Wallet/UPI Offers",
        couponCode: "PAYTM30"
    },
    {
        bankName: "PhonePe",
        paymentType: "UPI",
        merchant: "Swiggy",
        discountType: "Flat",
        discountValue: 75,
        minOrderValue: 199,
        startDate: admin.firestore.Timestamp.now(),
        endDate: admin.firestore.Timestamp.fromDate(new Date('2025-12-31')),
        isActive: true,
        description: "Flat ₹75 off on first UPI order",
        sourceUrl: "https://www.swiggy.com",
        dealScore: 80,
        dealBand: "Green",
        successCount: 356,
        failCount: 22,
        category: "Wallet/UPI Offers",
        couponCode: "PHONEPE75"
    }
];

// Function to add offers to Firestore
async function populateOffers() {
    console.log('Starting to populate Firestore with sample offers...');

    const batch = db.batch();

    sampleOffers.forEach((offer, index) => {
        const docRef = db.collection('offers').doc();
        batch.set(docRef, {
            ...offer,
            id: docRef.id,
            createdAt: admin.firestore.Timestamp.now(),
            updatedAt: admin.firestore.Timestamp.now()
        });
        console.log(`Added offer ${index + 1}/${sampleOffers.length}: ${offer.merchant} - ${offer.discountValue}${offer.discountType === 'Percentage' ? '%' : '₹'} off [${offer.category}]`);
    });

    await batch.commit();
    console.log('\n✅ Successfully added all sample offers to Firestore!');
    console.log(`Total offers added: ${sampleOffers.length}`);
    console.log('\nBreakdown by category:');
    console.log(`- Dining: ${sampleOffers.filter(o => o.category === 'Dining').length}`);
    console.log(`- Travel: ${sampleOffers.filter(o => o.category === 'Travel').length}`);
    console.log(`- Shopping: ${sampleOffers.filter(o => o.category === 'Shopping').length}`);
    console.log(`- Entertainment: ${sampleOffers.filter(o => o.category === 'Entertainment').length}`);
    console.log(`- Groceries: ${sampleOffers.filter(o => o.category === 'Groceries').length}`);
    console.log(`- Bill Pay & Recharges: ${sampleOffers.filter(o => o.category === 'Bill Pay & Recharges').length}`);
    console.log(`- Wallet/UPI Offers: ${sampleOffers.filter(o => o.category === 'Wallet/UPI Offers').length}`);
}

// Run the script
populateOffers()
    .then(() => {
        console.log('\n🎉 All done! You can now see these offers in your app.');
        process.exit(0);
    })
    .catch((error) => {
        console.error('Error populating offers:', error);
        process.exit(1);
    });
